### ISSUE TITLE
Suggestion: Market value and suggested upgrades

### ISSUE THREAD

**Issue by Kremath** [Ihellmasker/BDO-Planner#82] opened 2018-04-19 03:09 UTC
Add avg market prices for items and then have something like an 'ap goal' , 'dp goal' etc for like accuracy as well or even the new 'adventurer bonus' stat then have it suggest the best option for making the most change towards that goal for the least money.

Sort of like an 'optimize build' option or something or atleast something pointing out the weakest links in your gear comparatively to other pieces of gear near the same price.

**Comment by Ihellmasker** [comment] 2018-04-19 09:17
If you can make an API that can obtain the market prices from the servers efficiently and correctly, then we'd definitely consider implementing it. Until then, nope, also, duplicate of #71

**Closed by Ihellmasker** 2018-04-19 09:17 UTC
